---
# Path: .github/workflows/release.yml (for MyTestProject repository)
name: Documentation Generation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'templates/**/*.md'
      - 'templates/**/docfx.json'
      - 'templates/**/toc.yml'
      - 'templates/**/filterConfig.yml'
      - 'scripts/generate-docs.*'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'templates/**/*.md'
      - 'templates/**/docfx.json'
      - 'templates/**/toc.yml'
      - 'templates/**/filterConfig.yml'
      - 'scripts/generate-docs.*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run documentation generation script
        run: ./scripts/generate-docs.sh generate

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4